'use strict'

let dataObj = {
    'page1' : {/* html content */'html' : '<form action="" method="post" target="_self" id="forma">    <div data-enterInput="enterInput">        <div>            <div class="enterLabels">                <label for="login">Логин</label>            </div>            <div class="enterLabels">                <label for="password">Пароль</label>            </div>        </div>        <div>            <div class="enterLabels">                <input type="text" name="login" id="loginName">            </div>            <div class="enterLabels">                <input type="password" name="password" id="passwordLogin">            </div></div>    </div>    <div>        <input type="button" value="Войти" onclick="valid (document.getElementById ("forma"))"><input type="button" value="Зарегистрироваться" onclick="registr ()">    </div></form>',
    /* css content */'css' : "div[data-workBlock='WorkBlock'] {        display: flex;        flex-direction: row;        justify-content: center;        align-items: center;    }    [data-enterInput] {        display: flex;        flex-direction: row;        justify-content: center;        align-items: center;    }    .enterLabels {        margin-right: 2rem;        margin-bottom: 1rem;    }    #forma {        display: flex;        flex-direction: column;        justify-content: center;        align-items: center;    }",
    /* js content */ 'js' : "'use strict' function valid (form) {    let fail = false;    let login = form.login.value;    let password = form.password.value;    if (login == '' || login == ' ') {        fail = 'Вы не верно ввели логин'    } else if (password == '') {            fail = 'Вы не ввели пароль'        }    if (fail) {        alert (fail);    } else {        window.location = 'https://www.google.com'    }} function registr () {    let changeMom = document.getElementById ('workBlock');    let texting = '<div><input type='button' value='Войти' onclick='valid (document.getElementById ('forma'))'><input type='button' value='Зарегистрироваться' onclick='registr ()'></div>'    changeMom.innerHTML = texting;}"
},
'page2' : {/* html content */'html' : '<form action="" method="post" target="_self" id="forma"><div data-enterInput="enterInput"><div><div class="enterLabels"><label for="login">Пароль</label></div><div class="enterLabels"><label for="password">Повторите пароль пароль</label></div></div><div><div class="enterLabels"><input type="text" name="login" id="loginName"></div><div class="enterLabels"><input type="password" name="password" id="passwordLogin"></div></div></div><div><input type="button" value="Зарегистрироваться" onclick="registrProcess ()"></div></form>',
    /* css content */'css' : "div[data-workBlock='WorkBlock'] {        display: flex;        flex-direction: row;        justify-content: center;        align-items: center;    }    [data-enterInput] {        display: flex;        flex-direction: row;        justify-content: center;        align-items: center;    }    .enterLabels {        margin-right: 2rem;        margin-bottom: 1rem;    }    #forma {        display: flex;        flex-direction: column;        justify-content: center;        align-items: center;    }",
    /* js content */ 'js' : "'use strict' function valid (form) {    let fail = false;    let login = form.login.value;    let password = form.password.value;    if (login == '' || login == ' ') {        fail = 'Вы не верно ввели логин'    } else if (password == '') {            fail = 'Вы не ввели пароль'        }    if (fail) {        alert (fail);    } else {        window.location = 'https://www.google.com'    }} function registr () {    let changeMom = document.getElementById ('workBlock');    let texting = '<div><input type='button' value='Войти' onclick='valid (document.getElementById ('forma'))'><input type='button' value='Зарегистрироваться' onclick='registr ()'></div>'    changeMom.innerHTML = texting;}"
},};